### ISSUE TITLE
Does this script still work ? 

### ISSUE THREAD

**Issue by MSZ-Spyro** [jedrzejd/scrap-otomoto#7]
Hello, does it still work ? I am trying to use this but i get only empty csv files unfortunately...

**Comment by jedrzejd** [comment]
Problem was solved and now application is working.

**Comment by MSZ-Spyro** [comment]
Good to hear that, but at this point i have made my own :)

**Comment by MSZ-Spyro** [comment]
BTW
```carlinks = currentPage.find_all('article', class_='ooa-15j3s1f e1b25f6f0')```

Those classes are dynamic, so it will change in some time and it will still not work.

**Comment by jedrzejd** [comment]
This seems to be the best solution at the moment, the sections are dynamic and I have no idea how else to go about it.

**Comment by MSZ-Spyro** [comment]
I actually didnt find any better solution tho, just saying. You can check my repo (that i actually forked from someone else and changed it in the meantime) if you want. Im a lousy developer so there is a lot of bullshit in it and could be done better but it works and that is all i need. https://github.com/KrzesloSzatan/otomoto_olx-scraper (in the source repo there is also olx scrapper i didnt use so i got rid of it)
